name: 🐛 Bug Report
description: Create a report to help us improve Strapi Design System.
title: '[bug]: '
labels: ['issue: bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!
  - type: textarea
    attributes:
      label: What version of strapi-design-system are you using?
      placeholder: |
        - Npm version
        - Node.js version:
        - Strapi Design System version:
        - Browser:
    validations:
      required: true
  - type: textarea
    attributes:
      label: "What's Wrong?"
      description: A concise description of what you expected to happen (please provide screenshots).
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What you expected to happen
    validations:
      required: true
