name: 🤔 Request for Comments / Question
description: Submit an RFC or question
title: '[RFC]: '
labels: ['issue: discussion']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing an RFC or Question!
  - type: textarea
    attributes:
      label: Context
      description: A concise description of your problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: If it's an RFC what are you proposing?
  - type: textarea
    attributes:
      label: Reasons
      description: If it's an RFC _why_ do you think we should do this?
