name: 'Experimental Releases'

on:
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    if: github.repository == 'strapi/design-system'
    steps:
      - uses: actions/checkout@v4
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'
      - run: yarn
      - run: yarn build --ignore="@strapi/design-system-docs"
      - run: ./scripts/pre-publish.sh --yes
        env:
          VERSION: '0.0.0-${{ github.sha }}'
          DIST_TAG: experimental
